"""Offline test of the self-repair loop — Claude's extract + repair calls are mocked.

Demonstrates a real repair: extraction plans an SDTM domain the builtin generator can't
emit (MH/Medical History); validation's coverage check flags it; the repair step drops it; regeneration
then passes. No API key needed.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from protocol_to_data import loop as loop_mod  # noqa: E402
from protocol_to_data.loop import run_loop  # noqa: E402
from protocol_to_data.schemas import Arm, DomainPlan, ProtocolDesign, Visit  # noqa: E402


def _design(domains):
    return ProtocolDesign(
        study_id="HF-REPAIR", phase="3",
        arms=[Arm(name="DRUG-X"), Arm(name="PLACEBO", is_placebo=True)],
        visits=[Visit(name="BASELINE", day=1), Visit(name="WEEK4", day=28)],
        domains=[DomainPlan(domain=d) for d in domains],
    )


def _protocol_file(tmp_path) -> Path:
    p = tmp_path / "protocol.md"
    p.write_text("A Phase 3 HFrEF study with ECGs.")
    return p


def test_repair_loop_converges(tmp_path, monkeypatch):
    """MH is unproducible → flagged → dropped by repair → second pass passes."""
    unfixable = _design(["DM", "VS", "MH"])          # MH can't be generated by builtin
    fixed = _design(["DM", "VS"])                     # repair drops MH

    monkeypatch.setattr(loop_mod, "extract_design",
                        lambda *a, **k: unfixable.model_copy(deep=True))
    monkeypatch.setattr(loop_mod, "design_from_prompt",
                        lambda *a, **k: fixed.model_copy(deep=True))

    res = run_loop(_protocol_file(tmp_path), subjects=8, seed=1,
                   out_root=tmp_path / "out", max_repairs=2)

    assert res.report.passed, [f.message for f in res.report.findings]
    assert res.repair_attempts == 1
    assert res.design.domain_names() == ["DM", "VS"]  # MH gone after repair


def test_repair_bounded_when_unfixable(tmp_path, monkeypatch):
    """If repair never fixes the problem, the loop stops at max_repairs without faking success."""
    bad = _design(["DM", "VS", "MH"])
    monkeypatch.setattr(loop_mod, "extract_design", lambda *a, **k: bad.model_copy(deep=True))
    # repair returns the same broken design every time
    monkeypatch.setattr(loop_mod, "design_from_prompt", lambda *a, **k: bad.model_copy(deep=True))

    res = run_loop(_protocol_file(tmp_path), subjects=6, seed=1,
                   out_root=tmp_path / "out", max_repairs=2)

    assert not res.report.passed
    assert res.repair_attempts == 2  # tried the cap, then surfaced the report
    assert any(f.check == "coverage" and f.domain == "MH" for f in res.report.findings)


def test_manifest_written(tmp_path, monkeypatch):
    """A clean run persists run_manifest.json + validation_report.json for reproducibility."""
    good = _design(["DM", "VS", "AE"])
    monkeypatch.setattr(loop_mod, "extract_design", lambda *a, **k: good.model_copy(deep=True))

    res = run_loop(_protocol_file(tmp_path), subjects=8, seed=42,
                   out_root=tmp_path / "out", max_repairs=2)

    assert res.report.passed
    assert res.repair_attempts == 0
    assert (res.output_dir.parent / "run_manifest.json").exists()
    assert (res.output_dir.parent / "validation_report.json").exists()
